### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by gemixin** [zkiiito/node-sbrick-protocol#7]
Hi I am super new to Node.JS and on my Mac I tried installing with npm install s-brick protocol and I get this weird output:

[Terminal Saved Output.txt](https://github.com/zkiiito/node-sbrick-protocol/files/4014314/Terminal.Saved.Output.txt)

I tried running the `npm fund` command and `npm audit fix` but it makes no difference.

**Comment by zkiiito** [comment]
hey, you are having issues with noble. i think you can get more help with that here:
https://github.com/noble/noble
